### ISSUE TITLE
XML binding for VODML attribute to be serialised as XML attribute

### ISSUE THREAD

**Issue by pahjbo** [ivoa/vo-dml#23]

**Comment by glemson** [comment]
hat is meant by this? Would this be in contrast to binding to an XML element?

**Comment by pahjbo** [comment]
> What is meant by this? Would this be in contrast to binding to an XML element?

that was the idea - I had not realised that the description had not been saved! The motivation was to perhaps be able to represent some of the existing registry schema in VO-DML.

**Comment by glemson** [comment]
I tried that once, long time ago. Even before time of VO-URP. Main effect was to normalize the schema(s) in the IVOA a bit. See DM at Cambridge, MA interop and DM and VOTable meeting at Kyoto interop. Before the Cambridge interop I think we'd had a telecon of Registry group where I suggested same thing. thread starting here http://mail.ivoa.net/pipermail/registry/2003-November/003168.html

**Comment by pahjbo** [comment]
added in 0.5 release
