### ISSUE TITLE
make whether XML serialisation uses "wrapped" style for compositions configurable

### ISSUE THREAD

**Issue by pahjbo** [ivoa/vo-dml#66]
the for a particular composition the style could be
```
<thing>.....</thing>
<thing>..... </thing>
```

or 

```
<things>
   <thing>.....</thing>
   <thing>..... </thing>
</things>
```

The choice of style could be made configurable in the binding

**Comment by pdowler** [comment]
wrapped style much more naturally fits json serialization and I only ever use wrapped style in xsd. I would go as far as saying the other style (as used in VOTable) is hostile to having consistent serialization in different formats and should be avoided at all costs. The slight edge in compactness is not worth it.

**Comment by pahjbo** [comment]
I have just made wrapped the default (or at least it will be in 0.5.13)

the name of the `<things>` element is the attribute name of the composition
the name of the `<thing>` element is the name of the type of the composition

this seemed easier than trying to mess with plurals - so care is needed with naming in the vo-dml to make this "nice"

the old unwrapped style can be achieved in the binding file with an `<xml compositionStyle="unwrapped"/>`
